### ISSUE TITLE
No beacons returned when ranging 

### ISSUE THREAD

**Issue by okonon** [apility/phonegap-estimotebeacons#2]
@torrottum @thomas-alrek are you guys able to successfully range for beacons on android?

i am running into the issue where success calback is called with region object but with empty beacons array. but monitoring works fine for same region.

```
{
  region: {
    "identifier":"GLOBAL_REGION",
    "uuid":"B9407F30-F5F8-466E-AFF9-25556B57FE6D"
  }, 
  beacons: []
}
```

**Comment by okonon** [comment]
It appears that EstimoteCloud instance does not find my beacon by mac address... so i had to comment out related code in EstimoteBeacons.java

**Comment by thomas-alrek** [comment]
Hi. No, I am not currently able to get Ranging to work. It instantly makes the app crash. I haven't gotten around to debug it. I have just merged patches from various forks, but still nothing. If you where able to fix anything, I would love to get a pull request

**Comment by okonon** [comment]
It appears that estimote cloud doesn't recognize beacons and returns 404. This could be due to the race condition (just my guess) where app is not initialized Estimote SDK before making cloud request. My app does not crash though. iOS app was crashing for me unti I added Bluetooth-central background mode. So I am wondering if you need to check android permissions
